spring:
  web:
    locale: en
    resources:
      chain:
        strategy:
          content:
            enabled: true
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true

server:
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/xml
      - text/plain
      - text/css
      - text/javascript
      - application/javascript
      - application/json
      - application/xml
      - image/svg+xml

blog:
  content:
    host: 'http://localhost:8080'
    headers:
      report-uri: '${blog.content.host}/api/telemetry/csp'
      report-to: '{"group":"default","max_age":31536000,"endpoints":[{"url":"${blog.content.host}/api/telemetry/reports"}],"include_subdomains":true}'
