spring:
  web:
    locale: en
    resources:
      chain:
        strategy:
          content:
            enabled: true
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true

server:
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/xml
      - text/plain
      - text/css
      - text/javascript
      - application/javascript
      - application/json
      - application/xml
      - image/svg+xml

blog:
  content:
    supported-languages:
      - en
      - ja
